version: "3"
services:
  next:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    image: next-image
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1282M
        reservations:
          cpus: '0.125'
          memory: 64M
    container_name: next
  django:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    image: django-image
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1282M
        reservations:
          cpus: '0.125'
          memory: 64M
    container_name: django
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    image: nginx-image
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1282M
        reservations:
          cpus: '0.125'
          memory: 64M
    container_name: nginx
    ports:
      - "80:80/tcp"
    depends_on:
      - next
    links:
      - next