version: '3'
services:
  next:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    image: next-image
    container_name: next
  django:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    image: django-image
    container_name: django
    volumes:
      - static:/backend/static/
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    image: nginx-image
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static:/backend/static/
    depends_on:
      - next
    links:
      - next
volumes:
  static: