import type { NextPage } from 'next';
import Head from 'next/head';
import Top3 from '../components/main/Top3';
import styles from '../styles/Main.module.scss';
import Top3WithCategory from '../components/main/Top3WithCategory';
import Photo from '../components/main/Photo';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>이문세의 마굿간</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <div id="container">
                <main className={styles.content}>
                    <section className={`${styles.section_item} ${styles.item1}`}>
                        <Top3 title="베스트" />
                        <Top3 title="최근 게시글" />
                        <Top3 title="자유게시판" />
                        <Top3 title="새내기 인사" />
                    </section>
                    <section className={`${styles.section_item} ${styles.item2}`}>
                        <Top3WithCategory title="지역 게시판" category={['대전 + 충청', '대구 + 경북', '부산 + 울산 + 경남', '광주 + 전라 + 제주', '서울 + 경기 + 강원', '해외']} />
                    </section>
                    <section className={`${styles.section_item} ${styles.item3}`}>
                        <Photo title="이문세 앨범" />
                        <Photo title="마굿간 행사" />
                    </section>
                    <section className={`${styles.section_item} ${styles.item4}`}>
                        <Top3WithCategory title="취미 활동방" category={['야구 동호회', '여행 동호회', '산악 동호회']} />
                        <Top3WithCategory category={['당신들의 천국', '기사 스크랩', '후기감상실']} />
                    </section>
                </main>
            </div>
            {/* <main className={styles.main}> */}
            {/*     <h1 className={styles.title}> */}
            {/*         Welcome to */}
            {/*         <a href="https://nextjs.org">Next.js!</a> */}
            {/*     </h1> */}

            {/*     <p className={styles.description}> */}
            {/*         Get started by editing */}
            {/*         {' '} */}
            {/*         <code className={styles.code}>pages/Join.tsx</code> */}
            {/*     </p> */}

            {/*     <div className={styles.grid}> */}
            {/*         <a href="https://nextjs.org/docs" className={styles.card}> */}
            {/*             <h2>Documentation &rarr;</h2> */}
            {/*             <p>Find in-depth information about Next.js features and API.</p> */}
            {/*         </a> */}

            {/*         <a href="https://nextjs.org/learn" className={styles.card}> */}
            {/*             <h2>Learn &rarr;</h2> */}
            {/*             <p>Learn about Next.js in an interactive course with quizzes!</p> */}
            {/*         </a> */}

            {/*         <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}> */}
            {/*             <h2>Examples &rarr;</h2> */}
            {/*             <p>Discover and deploy boilerplate example Next.js projects.</p> */}
            {/*         </a> */}

            {/*         <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card}> */}
            {/*             <h2>Deploy &rarr;</h2> */}
            {/*             <p> */}
            {/*                 Instantly deploy your Next.js site to a public URL with Vercel. */}
            {/*             </p> */}
            {/*         </a> */}
            {/*     </div> */}
            {/* </main> */}

            {/* <footer className={styles.footer}> */}
            {/*     <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer"> */}
            {/*         Powered by */}
            {/*         {' '} */}
            {/*         <span className={styles.logo}> */}
            {/*             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
            {/*         </span> */}
            {/*     </a> */}
            {/* </footer> */}
        </>
    );
};

export default Home;
