# Generated by Django 4.1.2 on 2022-10-31 01:24

import apps.user.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('uid', models.CharField(max_length=15, null=True, unique=True)),
                ('name', models.CharField(max_length=16, null=True)),
                ('nickname', models.CharField(max_length=8, null=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True, verbose_name='email')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('residence', models.CharField(max_length=10, null=True)),
                ('homepage', models.URLField(null=True)),
                ('blog', models.URLField(null=True)),
                ('birth', models.DateField(null=True)),
                ('job', models.CharField(max_length=10, null=True)),
                ('profile', models.ImageField(null=True, upload_to=apps.user.models.image_path)),
                ('social', models.CharField(max_length=6, null=True)),
                ('mailing', models.BooleanField(default=False)),
                ('message', models.CharField(choices=[('OPN', 'allow all'), ('LMT', 'friend only'), ('CLS', 'disallow')], default='ALL', max_length=3)),
                ('sign_in', models.DateField(auto_now_add=True)),
                ('sign_out', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
